### ISSUE TITLE
可以弄成docker版的么？

### ISSUE THREAD

**Issue by xiongaox** [EvanTop/EvanNav#1]
如题

**Comment by EvanTop** [comment]
目前以我的技术水平还是做不到的，哈哈。如果有可能，希望你可以加加油。哈哈

**Comment by wang4386** [comment]
> 如题

```
version: '3.8'
services:
  evannav:
    image: qninq/evannav:latest
    container_name: evannav
    ports:
      - "3003:3003"
    restart: unless-stopped
    volumes:
      - ./data.json:/data.json
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3003"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
```
```
docker compose up -d
```
记得先把data.json放到docker-compose.yml同目录下
